version: '3.8'

services:
  spring-boot-app:
    container_name: book-app-container
    image: book-app.jar
    build: ./
    ports:
      - "9090:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres_db:5432/books_testing
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres-book-container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_testing
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: {}
